### ISSUE TITLE
Adding a column to sales_flat_order_item gives issues on a large table (>10GB)

### ISSUE THREAD

**Issue by igorwulff** [channelengine/magento#4]
For one of our clients we face a big problem when running the setup of this extension:

* It takes a lot of time to add a column to a large sales_flat_order_item table which causes a long downtime for the client with lost revenue.
* With our server configuration we are hitting the limits of our tmp diskspace size (10GB) for mysql. Basically stopping and blocking the installation.

A solution might be to normalize the fields you are adding in a separate table. This way there is no impact of an ALTER TABLE command and there are now issues while installing this for large Magento webshops.

I shall await your reply to this issue and we think it might be good to discuss this issue also through a phone call.

**Comment by christiaanderidder** [comment]
This issue has been resolved by removing the columns from the install scripts, because they are not required anymore. 2952fb6f8d486177cd576499c1af44877f52b2b5
