### ISSUE TITLE
Head.php

### ISSUE THREAD

**Issue by ischabf** [channelengine/magento#5]
`if(!isset($config['general'][$storeId]) || empty($config['general'][$storeId]['tenant'])) return false;`

Always returns false in our multistore setup.

It's looking if `$config['general'][$storeId]` is set, but this isn't set. It should look if `$config['general']['tenant']` is set.

**Comment by christiaanderidder** [comment]
Hi,

This issue has been resolved in 22734af1fef53ff3714d6c97bdd4979e911630fe and has been included in https://github.com/channelengine/magento/releases/tag/v5.4.1
